name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag trade-like-nancy:$(date +%s)

      - name: Push docker image to GHCR
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: trade-like-nancy
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          dockerfile: Dockerfile
          tags: latest
